# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: sci-dl\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-03-18 15:28+0800\n"
"PO-Revision-Date: 2021-03-18 11:57+0800\n"
"Last-Translator: soultoolman <soultoolman@gmail.com>\n"
"Language-Team: soultoolman <soultoolman@gmail.com>\n"
"Language: zh_CN\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: sci_dl.py:59
msgid "Unknown error occurred, please refer to log file to get more detail."
msgstr "发生未知错误，更多详请查看日志。"

#: sci_dl.py:130
msgid "malformed configuration file, can't find %s"
msgstr "损坏的配置文件，未能找到配置项%s"

#: sci_dl.py:147
msgid ""
"configuration file %s does not exists, please run \"sci-dl config init\" to "
"create it."
msgstr "配置文件%s不存在，请运行'sci-dl config init'来初始化。"

#: sci_dl.py:184
msgid "retrying..."
msgstr "重试中..."

#: sci_dl.py:185
msgid "download %s failure"
msgstr "%s下载失败"

#: sci_dl.py:199
msgid "invalid DOI %s"
msgstr "非法DOI号%s"

#: sci_dl.py:238
msgid ":green_book: SciHub base url"
msgstr ":green_book: SciHub地址"

#: sci_dl.py:243
msgid ":green_book: Invalid base_url %s"
msgstr ":green_book: 非法SciHub地址%s"

#: sci_dl.py:248
msgid ":green_book: Number of failure download retries"
msgstr ":green_book: 下载失败重试次数"

#: sci_dl.py:254
msgid ""
":green_book: invalid number of failure download retries %s, must between %s "
"and %s"
msgstr ":green_book: 非法下载失败重试次数%s，应该在%s和%s之间"

#: sci_dl.py:260
msgid ":green_book: Do you want to use a proxy?"
msgstr ":green_book: 想要使用代理吗？"

#: sci_dl.py:271
msgid ":green_book: Protocol of your proxy"
msgstr ":green_book: 代理协议"

#: sci_dl.py:278
msgid ":green_book: User of your proxy, leave blank if not need"
msgstr ":green_book: 代理用户名（如果没有就留空）"

#: sci_dl.py:284
msgid ":green_book: Password of your proxy, leave blank if not need"
msgstr ":green_book: 代理密码（如果没有就留空）"

#: sci_dl.py:291
msgid ":green_book: Host of your proxy"
msgstr ":green_book: 代理服务器地址"

#: sci_dl.py:300
msgid ":green_book: Invalid host %s"
msgstr ":green_book: 非法代理服务器地址%s"

#: sci_dl.py:305
msgid ":green_book: Port of your proxy"
msgstr ":green_book: 代理服务器端口"

#: sci_dl.py:310
msgid ":green_book: Invalid port %s, should between 1 and 65535"
msgstr ":green_book: 非法端口%s，应该介于1到65535之间"

#: sci_dl.py:315
msgid ":green_book: Log file"
msgstr ":green_book: 日志文件"

#: sci_dl.py:324
msgid ":green_book: Invalid log file %s"
msgstr ":green_book: 非法日志文件%s"

#: sci_dl.py:329
msgid ":green_book: Where you want to save PDF file"
msgstr ":green_book: PDF保存路径"

#: sci_dl.py:334
msgid ":green_book: Invalid directory %s"
msgstr ":green_book: 非法路径%s"

#: sci_dl.py:338
msgid ":green_book: Enable DEBUG mode?"
msgstr ":green_book: 开启调试模式？"

#: sci_dl.py:356
msgid ":green_book: Configurations saved, you can edit %s if needed."
msgstr ":green_book: 配置文件已保存到%s，如有需要可以手工修改。"

#: sci_dl.py:396
msgid ":green_book: Received DOI [bold][green]%s[/green][/bold]"
msgstr ":green_book: 收到DOI号[bold][green]%s[/green][/bold]"

#: sci_dl.py:405
msgid "Failed to parse PDF url of DOI %s"
msgstr "未能解析DOI号%s对应的PDF地址"

#: sci_dl.py:408
msgid ":green_book: Find PDF url %s"
msgstr ":green_book: 找到PDF地址%s"

#: sci_dl.py:414
#, fuzzy
msgid "Failed to Download PDF url %s of DOI %s"
msgstr ":green_book: 未能下载PDF地址%s，DOI号%s"

#: sci_dl.py:428
msgid ":green_book: Congratulations, PDF was saved to %s successfully."
msgstr ":green_book: 恭喜，PDF文件已经成功保存到%s。"
